import type { Team, TeamAbbr } from './types';

/**
 * 2026 team dataset. Power ratings are on a neutral-field points scale
 * (difference ≈ point spread). Attributes encode Ken Barkley's models:
 * DVOA/pass-defense ranks (prior year), elite-QB-season pedigree, and Mid-QB flags.
 *
 * NOTE: This is the seed/fallback layer. When a free odds API key is configured,
 * live lines override the market numbers; team profile attributes remain the
 * analytical backbone of the confidence model.
 */
export const TEAMS: Record<TeamAbbr, Team> = {
  ARI: {
    abbr: 'ARI',
    city: 'Arizona',
    name: 'Cardinals',
    conference: 'NFC',
    division: 'West',
    primary: '#97233F',
    secondary: '#000000',
    rating: -1.0,
    winTotal: 4.5,
    passDefRankPrev: 20,
    dvoaRankPrev: 24,
    qbHasEliteSeason: true,
    midQb: true,
    rookieQb: false,
  },
  ATL: {
    abbr: 'ATL',
    city: 'Atlanta',
    name: 'Falcons',
    conference: 'NFC',
    division: 'South',
    primary: '#A71930',
    secondary: '#000000',
    rating: 0.0,
    winTotal: 7.5,
    passDefRankPrev: 22,
    dvoaRankPrev: 19,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  BAL: {
    abbr: 'BAL',
    city: 'Baltimore',
    name: 'Ravens',
    conference: 'AFC',
    division: 'North',
    primary: '#241773',
    secondary: '#9E7C0C',
    rating: 6.0,
    winTotal: 11.5,
    passDefRankPrev: 13,
    dvoaRankPrev: 13,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  BUF: {
    abbr: 'BUF',
    city: 'Buffalo',
    name: 'Bills',
    conference: 'AFC',
    division: 'East',
    primary: '#00338D',
    secondary: '#C60C30',
    rating: 6.5,
    winTotal: 11.5,
    passDefRankPrev: 16,
    dvoaRankPrev: 8,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  CAR: {
    abbr: 'CAR',
    city: 'Carolina',
    name: 'Panthers',
    conference: 'NFC',
    division: 'South',
    primary: '#0085CA',
    secondary: '#101820',
    rating: -3.0,
    winTotal: 6.5,
    passDefRankPrev: 31,
    dvoaRankPrev: 28,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  CHI: {
    abbr: 'CHI',
    city: 'Chicago',
    name: 'Bears',
    conference: 'NFC',
    division: 'North',
    primary: '#0B162A',
    secondary: '#C83803',
    rating: 1.0,
    winTotal: 8.5,
    passDefRankPrev: 15,
    dvoaRankPrev: 16,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  CIN: {
    abbr: 'CIN',
    city: 'Cincinnati',
    name: 'Bengals',
    conference: 'AFC',
    division: 'North',
    primary: '#FB4F14',
    secondary: '#000000',
    rating: 2.0,
    winTotal: 9.5,
    passDefRankPrev: 29,
    dvoaRankPrev: 20,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  CLE: {
    abbr: 'CLE',
    city: 'Cleveland',
    name: 'Browns',
    conference: 'AFC',
    division: 'North',
    primary: '#311D00',
    secondary: '#FF3C00',
    rating: -3.5,
    winTotal: 5.5,
    passDefRankPrev: 12,
    dvoaRankPrev: 27,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: true,
  },
  DAL: {
    abbr: 'DAL',
    city: 'Dallas',
    name: 'Cowboys',
    conference: 'NFC',
    division: 'East',
    primary: '#003594',
    secondary: '#869397',
    rating: 1.0,
    winTotal: 9.5,
    passDefRankPrev: 31,
    dvoaRankPrev: 21,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  DEN: {
    abbr: 'DEN',
    city: 'Denver',
    name: 'Broncos',
    conference: 'AFC',
    division: 'West',
    primary: '#FB4F14',
    secondary: '#002244',
    rating: 4.0,
    winTotal: 10.5,
    passDefRankPrev: 6,
    dvoaRankPrev: 7,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  DET: {
    abbr: 'DET',
    city: 'Detroit',
    name: 'Lions',
    conference: 'NFC',
    division: 'North',
    primary: '#0076B6',
    secondary: '#B0B7BC',
    rating: 5.0,
    winTotal: 10.5,
    passDefRankPrev: 18,
    dvoaRankPrev: 3,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  GB: {
    abbr: 'GB',
    city: 'Green Bay',
    name: 'Packers',
    conference: 'NFC',
    division: 'North',
    primary: '#203731',
    secondary: '#FFB612',
    rating: 4.5,
    winTotal: 10.5,
    passDefRankPrev: 9,
    dvoaRankPrev: 11,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  HOU: {
    abbr: 'HOU',
    city: 'Houston',
    name: 'Texans',
    conference: 'AFC',
    division: 'South',
    primary: '#03202F',
    secondary: '#A71930',
    rating: 3.0,
    winTotal: 9.5,
    passDefRankPrev: 5,
    dvoaRankPrev: 4,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  IND: {
    abbr: 'IND',
    city: 'Indianapolis',
    name: 'Colts',
    conference: 'AFC',
    division: 'South',
    primary: '#002C5F',
    secondary: '#A2AAAD',
    rating: 1.0,
    winTotal: 8.5,
    passDefRankPrev: 14,
    dvoaRankPrev: 5,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  JAX: {
    abbr: 'JAX',
    city: 'Jacksonville',
    name: 'Jaguars',
    conference: 'AFC',
    division: 'South',
    primary: '#006778',
    secondary: '#D7A22A',
    rating: 1.5,
    winTotal: 8.5,
    passDefRankPrev: 10,
    dvoaRankPrev: 6,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  KC: {
    abbr: 'KC',
    city: 'Kansas City',
    name: 'Chiefs',
    conference: 'AFC',
    division: 'West',
    primary: '#E31837',
    secondary: '#FFB81C',
    rating: 5.0,
    winTotal: 11.5,
    passDefRankPrev: 8,
    dvoaRankPrev: 15,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  LV: {
    abbr: 'LV',
    city: 'Las Vegas',
    name: 'Raiders',
    conference: 'AFC',
    division: 'West',
    primary: '#000000',
    secondary: '#A5ACAF',
    rating: -2.0,
    winTotal: 6.5,
    passDefRankPrev: 17,
    dvoaRankPrev: 25,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  LAC: {
    abbr: 'LAC',
    city: 'Los Angeles',
    name: 'Chargers',
    conference: 'AFC',
    division: 'West',
    primary: '#0080C6',
    secondary: '#FFC20E',
    rating: 3.0,
    winTotal: 9.5,
    passDefRankPrev: 11,
    dvoaRankPrev: 17,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  LAR: {
    abbr: 'LAR',
    city: 'Los Angeles',
    name: 'Rams',
    conference: 'NFC',
    division: 'West',
    primary: '#003594',
    secondary: '#FFA300',
    rating: 7.0,
    winTotal: 11.5,
    passDefRankPrev: 1,
    dvoaRankPrev: 2,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  MIA: {
    abbr: 'MIA',
    city: 'Miami',
    name: 'Dolphins',
    conference: 'AFC',
    division: 'East',
    primary: '#008E97',
    secondary: '#FC4C02',
    rating: -1.0,
    winTotal: 4.5,
    passDefRankPrev: 28,
    dvoaRankPrev: 26,
    qbHasEliteSeason: true,
    midQb: true,
    rookieQb: false,
  },
  MIN: {
    abbr: 'MIN',
    city: 'Minnesota',
    name: 'Vikings',
    conference: 'NFC',
    division: 'North',
    primary: '#4F2683',
    secondary: '#FFC62F',
    rating: 1.0,
    winTotal: 8.5,
    passDefRankPrev: 19,
    dvoaRankPrev: 18,
    qbHasEliteSeason: true,
    midQb: true,
    rookieQb: false,
  },
  NE: {
    abbr: 'NE',
    city: 'New England',
    name: 'Patriots',
    conference: 'AFC',
    division: 'East',
    primary: '#002244',
    secondary: '#C60C30',
    rating: 2.5,
    winTotal: 9.5,
    passDefRankPrev: 25,
    dvoaRankPrev: 9,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  NO: {
    abbr: 'NO',
    city: 'New Orleans',
    name: 'Saints',
    conference: 'NFC',
    division: 'South',
    primary: '#D3BC8D',
    secondary: '#101820',
    rating: -4.0,
    winTotal: 5.5,
    passDefRankPrev: 23,
    dvoaRankPrev: 30,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: true,
  },
  NYG: {
    abbr: 'NYG',
    city: 'New York',
    name: 'Giants',
    conference: 'NFC',
    division: 'East',
    primary: '#0B2265',
    secondary: '#A71930',
    rating: -2.0,
    winTotal: 7.5,
    passDefRankPrev: 21,
    dvoaRankPrev: 29,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: false,
  },
  NYJ: {
    abbr: 'NYJ',
    city: 'New York',
    name: 'Jets',
    conference: 'AFC',
    division: 'East',
    primary: '#125740',
    secondary: '#000000',
    rating: -1.5,
    winTotal: 5.5,
    passDefRankPrev: 32,
    dvoaRankPrev: 22,
    qbHasEliteSeason: true,
    midQb: true,
    rookieQb: false,
  },
  PHI: {
    abbr: 'PHI',
    city: 'Philadelphia',
    name: 'Eagles',
    conference: 'NFC',
    division: 'East',
    primary: '#004C54',
    secondary: '#A5ACAF',
    rating: 5.5,
    winTotal: 11.5,
    passDefRankPrev: 7,
    dvoaRankPrev: 14,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  PIT: {
    abbr: 'PIT',
    city: 'Pittsburgh',
    name: 'Steelers',
    conference: 'AFC',
    division: 'North',
    primary: '#FFB612',
    secondary: '#101820',
    rating: 1.0,
    winTotal: 8.5,
    passDefRankPrev: 4,
    dvoaRankPrev: 12,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  SF: {
    abbr: 'SF',
    city: 'San Francisco',
    name: '49ers',
    conference: 'NFC',
    division: 'West',
    primary: '#AA0000',
    secondary: '#B3995D',
    rating: 4.0,
    winTotal: 10.5,
    passDefRankPrev: 26,
    dvoaRankPrev: 10,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  SEA: {
    abbr: 'SEA',
    city: 'Seattle',
    name: 'Seahawks',
    conference: 'NFC',
    division: 'West',
    primary: '#002244',
    secondary: '#69BE28',
    rating: 4.5,
    winTotal: 9.5,
    passDefRankPrev: 14,
    dvoaRankPrev: 1,
    qbHasEliteSeason: true,
    midQb: true,
    rookieQb: false,
  },
  TB: {
    abbr: 'TB',
    city: 'Tampa Bay',
    name: 'Buccaneers',
    conference: 'NFC',
    division: 'South',
    primary: '#D50A0A',
    secondary: '#34302B',
    rating: 2.0,
    winTotal: 9.5,
    passDefRankPrev: 24,
    dvoaRankPrev: 23,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
  TEN: {
    abbr: 'TEN',
    city: 'Tennessee',
    name: 'Titans',
    conference: 'AFC',
    division: 'South',
    primary: '#0C2340',
    secondary: '#4B92DB',
    rating: -3.0,
    winTotal: 6.5,
    passDefRankPrev: 30,
    dvoaRankPrev: 31,
    qbHasEliteSeason: false,
    midQb: true,
    rookieQb: true,
  },
  WAS: {
    abbr: 'WAS',
    city: 'Washington',
    name: 'Commanders',
    conference: 'NFC',
    division: 'East',
    primary: '#5A1414',
    secondary: '#FFB612',
    rating: 2.0,
    winTotal: 9.5,
    passDefRankPrev: 27,
    dvoaRankPrev: 32,
    qbHasEliteSeason: true,
    midQb: false,
    rookieQb: false,
  },
};

export const TEAM_LIST: Team[] = Object.values(TEAMS);

export function teamName(abbr: TeamAbbr): string {
  const t = TEAMS[abbr];
  return `${t.city} ${t.name}`;
}

export function teamShort(abbr: TeamAbbr): string {
  return TEAMS[abbr].name;
}
